name: MonoGS
channels:
  - conda-forge
  - nvidia
dependencies:
  - ninja
  - cuda-toolkit=12.1
  - pip:
      - --extra-index-url https://download.pytorch.org/whl/cu128

      - torch==2.10.0+cu128
      - torchvision==0.19.1+cu128

      - numpy<2

      - plyfile==0.8.1
      - tqdm
      - opencv-python==4.8.1.78
      - munch
      - trimesh
      - evo==1.11.0
      - open3d==0.19.0
      - torchmetrics
      - imgviz
      - lpips
      - rich
      - wandb
      - PyOpenGL
      - glfw
      - PyGLM
